# both paths will be overwritten in the filling application
dsm_path: "path/to/dsm"
output_dir: "path/to/output"

# everything else will be used directly as-is

#-------------------------#
#         Options         #
#-------------------------#


max_object_size : 16
# If True, keep the intermediate results
developer_mode : False


#-------------------------#
#    Advanced settings    #
#-------------------------#
# [Optional] - Altimetric height accuracy of the input DSM (m). If null, use the default value: 2*planimetric resolution
dsm_z_accuracy: null
# [Optional] - Maximum slope of the observed landscape terrain (%)
# former slope_threshold
max_ground_slope: 2.0
# [Optional] - If True, activate the ground pre-detection
activate_ground_anchors : False
# [Optional] - If True, keep the intermediate results
developer_mode : False


#-------------------------#
# Bulldozer core settings #
#-------------------------#
# /!\ Modify those data at your own risk (it is suggested to keep the default values) /!\

# [Optional] - DtmExtraction parameters
# former uniform_filter_size
cloth_tension_force : 3
prevent_unhook_iter : 10
num_outer_iter : 50
num_inner_iter : 10



