# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set os required and python version (required)
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

# add projet [docs] extra url dependencies in sphinx RTD virtualenv
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/source/conf.py