FROM cnes/cars-jupyter:latest
LABEL maintainer="CNES"

WORKDIR /cars/tutorials/

# set a local version of reveal.js into /cars/tutorials for slides
RUN git clone https://github.com/hakimel/reveal.js.git \
  && jupyter nbconvert main_tutorial.ipynb --to slides --reveal-prefix reveal.js \
  && cp main_tutorial.slides.html index.html
  
ENTRYPOINT ["python", "-m", "http.server", "8000"]
