#!/bin/sh
# Dummy gdal-config file taken from S1 Tiling in order to help
# installing gdal python bindings on top of OTB binary releases.
#
# https://gitlab.orfeo-toolbox.org/s1-tiling/s1tiling/-/blob/develop/s1tiling/resources/gdal-config
#
CONFIG_PREFIX="$(dirname "$(dirname "$(readlink -f "$0")")")"
CONFIG_LIBS="-L${CONFIG_PREFIX}/lib -lgdal"
CONFIG_DEP_LIBS=" -lIlmImf -lImath -lHalf -lIex -lIexMath -lIlmThread -lpthread -lcrypto -L${CONFIG_PREFIX}/lib -lgeos_c -lsqlite3 -lexpat -lopenjp2 -lnetcdf -lhdf5  -lmfhdfalt -ldfalt -ljpeg -lgeotiff -ltiff -lpng -lproj -lsqlite3  -lz -lpthread -lm -lrt -ldl    -lcurl                  "
CONFIG_CFLAGS="-I${CONFIG_PREFIX}/include"
CONFIG_DATA="${CONFIG_PREFIX}/share/gdal"
# Automatically extract version number from gdal_version.h shipped with OTB
# Test 1. gdal-config prefix + include/gdal_version-h (normal OTB install)
# and  2. gdal-config prefix + include/gdal/gdal_version-h (gdal ubuntu package install)
# Or setup a default version > 3.1 (to be updated with local gdal install version)
GDAL_VERSION_FILE1="${CONFIG_PREFIX}/include/gdal_version.h"
GDAL_VERSION_FILE2="${CONFIG_PREFIX}/include/gdal/gdal_version.h"
if [ -f "$GDAL_VERSION_FILE1" ]; then
		CONFIG_VERSION="$(awk '/define GDAL_RELEASE_NAME/ {gsub(/"/, "", $4); print $4}' "${GDAL_VERSION_FILE1}")"
elif [ -f "$GDAL_VERSION_FILE2" ]; then
		CONFIG_VERSION="$(awk '/define GDAL_RELEASE_NAME/ {gsub(/"/, "", $4); print $4}' "${GDAL_VERSION_FILE2}")"
else
		CONFIG_VERSION="3.2.2"
fi
CONFIG_OGR_ENABLED=yes
CONFIG_GNM_ENABLED=yes
CONFIG_FORMATS="derived gtiff hfa mem vrt  aaigrid adrg aigrid airsar arg blx bmp bsb cals ceos ceos2 coasp cosar ctg dimap dted e00grid elas envisat ers fit gff gsg gxf hf2 idrisi ignfheightasciigrid ilwis ingr iris iso8211 jaxapalsar jdem kmlsuperoverlay l1b leveller map mrf msgn ngsgeoid nitf northwood pds prf r raw rmf rs2 safe saga sdts sentinel2 sgi sigdem srtmhgt terragen til tsx usgsdem xpm xyz zmap rik ozi grib eeda plmosaic rda wcs wms wmts daas rasterlite mbtiles pdf exr openjpeg netcdf hdf5 hdf4 jpeg png  pcidsk"
usage()
{
	cat <<EOF
Usage: gdal-config [OPTIONS]
Options:
	[--prefix[=DIR]]
	[--libs]
	[--dep-libs]
	[--cflags]
	[--datadir]
	[--version]
	[--ogr-enabled]
	[--gnm-enabled]
	[--formats]
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi

case $1 in
  --libs)
    echo $CONFIG_LIBS
    ;;

  --dep-libs)
    echo $CONFIG_DEP_LIBS
    ;;

  --cflags)
    echo $CONFIG_CFLAGS
    ;;

  --datadir)
    echo $CONFIG_DATA
    ;;

  --prefix)
    echo $CONFIG_PREFIX
    ;;

  --version)
    echo $CONFIG_VERSION
    ;;

  --ogr-enabled)
    echo yes
    ;;

  --gnm-enabled)
    echo $CONFIG_GNM_ENABLED
    ;;

  --formats)
    echo $CONFIG_FORMATS
    ;;

  *)
    usage 1 1>&2
    ;;

esac
