#!/bin/sh
CONFIG_LIBS="-L/usr/local/otb/lib -lgdal"
CONFIG_DEP_LIBS=" -L/usr/local/otb/lib -lgeos_c -L/usr/local/otb/lib -lsqlite3 -L/usr/local/otb/lib -lexpat -L/usr/local/otb/lib -lopenjp2   -L/usr/local/otb/lib -lnetcdf -lmfhdfalt -ldfalt -lhdf5_hl -lhdf5 -ldl -lm -lz -lcurl -L/usr/local/otb/lib -lhdf5  -L/usr/local/otb/lib -lmfhdfalt -ldfalt -L/usr/local/otb -L/usr/local/otb/lib -ljpeg -L/usr/local/otb/lib -lgeotiff -L/usr/local/otb/lib -ltiff -L/usr/local/otb -L/usr/local/otb/lib -lpng -lz -L/usr/local/otb -L/usr/local/otb/lib -lpthread -lm -lrt -ldl    -L/usr/local/otb/lib -lcurl                 "
CONFIG_PREFIX="/usr/local/otb/"
CONFIG_CFLAGS="-I/usr/local/otb/include"
CONFIG_DATA="/usr/local/otb/share/gdal"
CONFIG_VERSION="3.0.4"
CONFIG_OGR_ENABLED=yes
CONFIG_GNM_ENABLED=yes
CONFIG_FORMATS=" gxf gtiff hfa aigrid aaigrid ceos ceos2 iso8211 xpm sdts raw dted mem jdem envisat elas fit vrt usgsdem l1b nitf bmp airsar rs2 ilwis rmf leveller sgi srtmhgt idrisi gsg ingr ers jaxapalsar dimap gff cosar pds adrg coasp tsx terragen blx msgn til r northwood saga xyz hf2 kmlsuperoverlay ctg e00grid zmap ngsgeoid iris map cals safe sentinel2 derived prf sigdem ignfheightasciigrid mrf wcs wms plmosaic wmts rda eeda grib bsb openjpeg netcdf hdf5 hdf4 jpeg png  pcidsk rik ozi pdf rasterlite mbtiles arg"
usage()
{
        cat <<EOF
Usage: gdal-config [OPTIONS]
Options:
        [--prefix[=DIR]]
        [--libs]
        [--dep-libs]
        [--cflags]
        [--datadir]
        [--version]
        [--ogr-enabled]
        [--gnm-enabled]
        [--formats]
EOF
        exit $1
}

if test $# -eq 0; then
        usage 1 1>&2
fi

case $1 in
  --libs)
    echo $CONFIG_LIBS
    ;;

  --dep-libs)
    echo $CONFIG_DEP_LIBS
    ;;

  --cflags)
    echo $CONFIG_CFLAGS
    ;;

  --datadir)
    echo $CONFIG_DATA
    ;;

  --prefix)
    echo $CONFIG_PREFIX
    ;;

  --version)
    echo $CONFIG_VERSION
    ;;

  --ogr-enabled)
    echo yes
    ;;

  --gnm-enabled)
    echo $CONFIG_GNM_ENABLED
    ;;

  --formats)
    echo $CONFIG_FORMATS
    ;;

  *)
    usage 1 1>&2
    ;;

esac
