---
applications:
  resolution_4:
    application_name:
      method: first_method
      parameter1: 26
      parameter2: 0.9
  resolution_1:
    application_name:
      method: second_method
      parameter1: 8
      parameter2: 0.2
