---
applications:
  point_cloud_outlier_removal.1:
    method: small_components
    on_ground_margin: 10
    save_intermediate_data: true
  point_cloud_outlier_removal.2:
    method: statistical
    k: 10
    save_intermediate_data: true
