---
inputs:
  sensors:
    one:
      image: img1.tif
      geomodel: img1.geom
      color: color1.tif
    two:
      image: img2.tif
      geomodel: img2.geom
orchestrator:
  mode: multiprocessing
  nb_workers: 110
  max_ram_per_worker: 6000
output:
  directory: outresults
