---
inputs:
  sensors:
    left:
      image:
        loader: pivot_image
        bands:
          b0:
            path: left_image.tif
            band: 0
          b1:
            path: left_image.tif
            band: 1
          b2:
            path: left_image.tif
            band: 2
        no_data: 0
      geomodel:
        path: left_image.geom
        model_type: RPC
      mask: left_mask.tif
      classification:
        loader: pivot_classif
        path: left_classif.tif
        filling:
          fill_with_geoid: null
          interpolate_from_borders: null
          fill_with_endogenous_dem: null
          fill_with_exogenous_dem: null
    right:
      image:
        loader: pivot_image
        bands:
          b0:
            path: left_image.tif
            band: 0
          b1:
            path: left_image.tif
            band: 1
          b2:
            path: left_image.tif
            band: 2
        no_data: 0
      geomodel:
        path: right_image.geom
        model_type: RPC
      mask: right_mask.tif
      classification:
        loader: pivot_classif
        path: right_classif.tif
        filling:
          fill_with_geoid: null
          interpolate_from_borders: null
          fill_with_endogenous_dem: null
          fill_with_exogenous_dem: null
  pairing:
  - - left
    - right
  initial_elevation:
    dem: N43E007.hgt
    geoid: egm96.grd
  roi: 
advanced:
  save_intermediate_data: true
  epipolar_resolutions:
  - 16
  - 4
  - 1
  land_cover_map: global_land_cover_map.tif
  keep_low_res_dir: true
  debug_with_roi: false
  classification_to_configuration_mapping: config_mapping.json
  phasing: 
  use_endogenous_dem: false
  merging: false
  dsm_merging_tile_size: 4000
  ground_truth_dsm: {}
  epipolar_a_priori: 
  terrain_a_priori: 
  geometry_plugin: SharelocGeometry
  pipeline: default
output:
  directory: outresults
  auxiliary:
    image:
     - b0
     - b1
     - b2
    classification: 
      1: 1
      2: 2
      3: 3
      4: 4
    dem_min: true
    dem_max: true
    dem_median: true
    weights: false
    mask: false
    performance_map:
    - 0
    - 0.968
    - 1.13375
    - 1.295
    - 1.604
    - 2.423
    - 3.428
    contributing_pair: false
    filling: 
      1: fill_with_geoid
      2: interpolate_from_borders
      3: fill_with_endogenous_dem
      4: fill_with_exogenous_dem
    ambiguity: false
  product_level:
  - dsm
  geoid: true
  epsg: 
  resolution: 0.5
  save_by_pair: true
orchestrator:
  mode: multiprocessing
  nb_workers: 5
  max_ram_per_worker: 2000
  mp_mode: forkserver
  task_timeout: 600
  max_tasks_per_worker: 10
  dump_to_disk: true
  per_job_timeout: 600
  factorize_tasks: true
  profiling:
     mode: cars_profiling
     loop_testing: false
applications:
  '1':
    grid_generation:
      save_intermediate_data: true
      method: epipolar
      epi_step: 30
    resampling:
      save_intermediate_data: true
      method: bicubic
      strip_height: 60
      interpolator_image: bicubic
      interpolator_classif: nearest
      interpolator_mask: nearest
      step: 500
    ground_truth_reprojection:
      save_intermediate_data: true
    dense_match_filling:
      save_intermediate_data: true
      method: zero_padding
      classification: 
      fill_valid_pixels: true
    sparse_matching:
      save_intermediate_data: true
      method: sift
      disparity_margin: 0.02
      elevation_delta_lower_bound: -500
      decimation_factor: 30
      elevation_delta_upper_bound: 1000
      strip_margin: 10
      epipolar_error_upper_bound: 10
      epipolar_error_maximum_bias: 150
      minimum_nb_matches: 90
      sift_matching_threshold: 0.7
      sift_n_octave: 8
      sift_n_scale_per_octave: 3
      sift_peak_threshold: 4
      sift_edge_threshold: 10
      sift_magnification: 7
      sift_window_size: 2
      sift_back_matching: true
      match_filter_knn: 25
      match_filter_constant: 0
      match_filter_mean_factor: 1.3
      match_filter_dev_factor: 3
      used_band: b0
      disparity_bounds_estimation:
        activated: true
        percentile: 1
        lower_margin: 500
        upper_margin: 1000
    dense_matching:
      save_intermediate_data: true
      method: auto
      min_epi_tile_size: 300
      max_epi_tile_size: 1500
      epipolar_tile_margin_in_percent: 60
      classification_fusion_margin: -1
      min_elevation_offset: 
      max_elevation_offset: 
      denoise_disparity_map: false
      confidence_filtering:
        activated: true
        bounds_ratio_threshold: 0.2
        risk_ratio_threshold: 0.8
        bounds_range_threshold: 4
        risk_range_threshold: 12
        nan_threshold: 0.2
        win_nanratio: 20
      disp_min_threshold: 
      disp_max_threshold: 
      perf_eta_max_ambiguity: 0.99
      perf_eta_max_risk: 0.25
      perf_eta_step: 0.04
      perf_ambiguity_threshold: 0.6
      use_cross_validation: fast
      use_global_disp_range: false
      local_disp_grid_step: 10
      disp_range_propagation_filter_size: 50
      epi_disp_grid_tile_size: 800
      required_bands:
      - b0
      used_band: b0
      threshold_disp_range_to_borders: false
      generate_ambiguity: true
      performance_map_method:
      - risk
      loader: pandora
      loader_conf:
        input: {}
        pipeline:
          matching_cost:
            matching_cost_method: census
            window_size: 5
            subpix: 1
            band: b0
          optimization:
            optimization_method: sgm
            overcounting: false
            penalty:
              P1: 8
              P2: 32
              p2_method: constant
              penalty_method: sgm_penalty
          cost_volume_confidence.cars_1:
            confidence_method: ambiguity
            eta_max: 0.99
            eta_step: 0.04
          cost_volume_confidence.cars_2:
            confidence_method: risk
            eta_max: 0.25
            eta_step: 0.04
          disparity:
            disparity_method: wta
            invalid_disparity: NaN
          refinement:
            refinement_method: vfit
          filter:
            filter_method: median
            filter_size: 3
          validation:
            validation_method: cross_checking_fast
    triangulation:
      save_intermediate_data: true
      method: line_of_sight_intersection
      snap_to_img1: false
    dem_generation:
      save_intermediate_data: true
      method: bulldozer_on_raster
      resolution: 0.5
      margin:
      - 0.1
      - 500
      morphological_filters_size: 30
      preprocessing_median_filter_size: 5
      postprocessing_median_filter_size: 7
      dem_median_downscale: 10
      dem_min_max_downscale: 2
      fillnodata_max_search_distance: 50
      min_dem: -500
      max_dem: 1000
      height_margin: 20
      bulldozer_max_object_size: 8
      disable_bulldozer: false
      compute_stats: true
      coregistration: true
      coregistration_max_shift: 180
    point_cloud_outlier_removal.1:
      save_intermediate_data: true
      method: small_components
      save_by_pair: false
      on_ground_margin: 11
      connection_distance: 3
      nb_points_threshold: 50
      clusters_distance_threshold: 
      half_epipolar_size: 5
    point_cloud_outlier_removal.2:
      save_intermediate_data: true
      method: statistical
      save_by_pair: false
      use_median: true
      k: 50
      filtering_constant: 0
      mean_factor: 1.3
      std_dev_factor: 3
      half_epipolar_size: 5
    pc_denoising:
      save_intermediate_data: true
    point_cloud_rasterization:
      save_intermediate_data: true
      method: simple_gaussian
      dsm_radius: 1
      sigma: 
      grid_points_division_factor: 
      dsm_no_data: -32768
      texture_no_data: 
      texture_dtype: 
      msk_no_data: 255
    auxiliary_filling:
      method: auxiliary_filling_from_sensors
      mode: fill_nan
      texture_interpolator: linear
      activated: false
      use_mask: true
      save_intermediate_data: false
  '4':
    grid_generation:
      save_intermediate_data: true
      method: epipolar
      epi_step: 10
    resampling:
      save_intermediate_data: true
      method: bicubic
      strip_height: 60
      interpolator_image: bicubic
      interpolator_classif: nearest
      interpolator_mask: nearest
      step: 500
    ground_truth_reprojection:
      save_intermediate_data: true
    dense_match_filling:
      save_intermediate_data: true
      method: zero_padding
      classification: 
      fill_valid_pixels: true
    sparse_matching:
      save_intermediate_data: true
      method: sift
      disparity_margin: 0.02
      elevation_delta_lower_bound: -500
      decimation_factor: 30
      elevation_delta_upper_bound: 1000
      strip_margin: 10
      epipolar_error_upper_bound: 10
      epipolar_error_maximum_bias: 150
      minimum_nb_matches: 90
      sift_matching_threshold: 0.7
      sift_n_octave: 8
      sift_n_scale_per_octave: 3
      sift_peak_threshold: 4
      sift_edge_threshold: 10
      sift_magnification: 7
      sift_window_size: 2
      sift_back_matching: true
      match_filter_knn: 25
      match_filter_constant: 0
      match_filter_mean_factor: 1.3
      match_filter_dev_factor: 3
      used_band: b0
      disparity_bounds_estimation:
        activated: true
        percentile: 1
        lower_margin: 500
        upper_margin: 1000
    dense_matching:
      confidence_filtering:
        activated: false
        bounds_ratio_threshold: 0.2
        risk_ratio_threshold: 0.8
        bounds_range_threshold: 4
        risk_range_threshold: 12
        nan_threshold: 0.2
        win_nanratio: 20
      performance_map_method:
      - risk
      - intervals
      save_intermediate_data: true
      method: auto
      min_epi_tile_size: 300
      max_epi_tile_size: 1500
      epipolar_tile_margin_in_percent: 60
      classification_fusion_margin: -1
      min_elevation_offset: 
      max_elevation_offset: 
      denoise_disparity_map: false
      disp_min_threshold: 
      disp_max_threshold: 
      perf_eta_max_ambiguity: 0.99
      perf_eta_max_risk: 0.25
      perf_eta_step: 0.04
      perf_ambiguity_threshold: 0.6
      use_cross_validation: fast
      use_global_disp_range: false
      local_disp_grid_step: 10
      disp_range_propagation_filter_size: 50
      epi_disp_grid_tile_size: 800
      required_bands:
      - b0
      used_band: b0
      threshold_disp_range_to_borders: false
      generate_ambiguity: true
      loader: pandora
      loader_conf:
        input: {}
        pipeline:
          matching_cost:
            matching_cost_method: census
            window_size: 5
            subpix: 1
            band: b0
          optimization:
            optimization_method: sgm
            overcounting: false
            penalty:
              P1: 8
              P2: 32
              p2_method: constant
              penalty_method: sgm_penalty
          cost_volume_confidence.cars_1:
            confidence_method: ambiguity
            eta_max: 0.99
            eta_step: 0.04
          cost_volume_confidence.cars_2:
            confidence_method: risk
            eta_max: 0.25
            eta_step: 0.04
          cost_volume_confidence.cars_3:
            confidence_method: interval_bounds
          disparity:
            disparity_method: wta
            invalid_disparity: NaN
          refinement:
            refinement_method: vfit
          filter:
            filter_method: median
            filter_size: 3
          validation:
            validation_method: cross_checking_fast
          filter.cars_3:
            filter_method: median_for_intervals
            filter_size: 3
            interval_indicator: cars_3
            regularization: true
            ambiguity_indicator: cars_1
    triangulation:
      save_intermediate_data: true
      method: line_of_sight_intersection
      snap_to_img1: false
    dem_generation:
      save_intermediate_data: true
      method: bulldozer_on_raster
      resolution: 1
      margin:
      - 0.1
      - 707.1067811865476
      morphological_filters_size: 30
      preprocessing_median_filter_size: 5
      postprocessing_median_filter_size: 7
      dem_median_downscale: 10
      dem_min_max_downscale: 2
      fillnodata_max_search_distance: 50
      min_dem: -500
      max_dem: 1000
      height_margin: 28.284271247461902
      bulldozer_max_object_size: 8
      disable_bulldozer: false
      compute_stats: true
      coregistration: true
      coregistration_max_shift: 180
    point_cloud_outlier_removal.1:
      save_intermediate_data: true
      method: small_components
      save_by_pair: false
      on_ground_margin: 11
      connection_distance: 6
      nb_points_threshold: 50
      clusters_distance_threshold: 
      half_epipolar_size: 5
    point_cloud_outlier_removal.2:
      save_intermediate_data: true
      method: statistical
      save_by_pair: false
      use_median: true
      k: 50
      filtering_constant: 0
      mean_factor: 1.3
      std_dev_factor: 3
      half_epipolar_size: 5
    pc_denoising:
      save_intermediate_data: true
    point_cloud_rasterization:
      save_intermediate_data: true
      method: simple_gaussian
      dsm_radius: 1
      sigma: 
      grid_points_division_factor: 
      dsm_no_data: -32768
      texture_no_data: 
      texture_dtype: 
      msk_no_data: 255
    auxiliary_filling:
      method: auxiliary_filling_from_sensors
      mode: fill_nan
      texture_interpolator: linear
      activated: false
      use_mask: true
      save_intermediate_data: false
  '16':
    grid_generation:
      save_intermediate_data: true
      method: epipolar
      epi_step: 20
    resampling:
      save_intermediate_data: true
      method: bicubic
      strip_height: 60
      interpolator_image: bicubic
      interpolator_classif: nearest
      interpolator_mask: nearest
      step: 500
    ground_truth_reprojection:
      save_intermediate_data: true
    dense_match_filling:
      save_intermediate_data: true
      method: zero_padding
      classification: 
      fill_valid_pixels: true
    sparse_matching:
      save_intermediate_data: true
      method: sift
      disparity_margin: 0.02
      elevation_delta_lower_bound: -500
      decimation_factor: 30
      elevation_delta_upper_bound: 1000
      strip_margin: 10
      epipolar_error_upper_bound: 10
      epipolar_error_maximum_bias: 150
      minimum_nb_matches: 90
      sift_matching_threshold: 0.7
      sift_n_octave: 8
      sift_n_scale_per_octave: 3
      sift_peak_threshold: 4
      sift_edge_threshold: 10
      sift_magnification: 7
      sift_window_size: 2
      sift_back_matching: true
      match_filter_knn: 25
      match_filter_constant: 0
      match_filter_mean_factor: 1.3
      match_filter_dev_factor: 3
      used_band: b0
      disparity_bounds_estimation:
        activated: true
        percentile: 1
        lower_margin: 500
        upper_margin: 1000
    dense_matching:
      confidence_filtering:
        activated: false
        bounds_ratio_threshold: 0.2
        risk_ratio_threshold: 0.8
        bounds_range_threshold: 4
        risk_range_threshold: 12
        nan_threshold: 0.2
        win_nanratio: 20
      performance_map_method:
      - risk
      - intervals
      save_intermediate_data: true
      method: auto
      min_epi_tile_size: 300
      max_epi_tile_size: 1500
      epipolar_tile_margin_in_percent: 60
      classification_fusion_margin: -1
      min_elevation_offset: 
      max_elevation_offset: 
      denoise_disparity_map: false
      disp_min_threshold: 
      disp_max_threshold: 
      perf_eta_max_ambiguity: 0.99
      perf_eta_max_risk: 0.25
      perf_eta_step: 0.04
      perf_ambiguity_threshold: 0.6
      use_cross_validation: fast
      use_global_disp_range: false
      local_disp_grid_step: 10
      disp_range_propagation_filter_size: 50
      epi_disp_grid_tile_size: 800
      required_bands:
      - b0
      used_band: b0
      threshold_disp_range_to_borders: false
      generate_ambiguity: true
      loader: pandora
      loader_conf:
        input: {}
        pipeline:
          matching_cost:
            matching_cost_method: census
            window_size: 5
            subpix: 1
            band: b0
          optimization:
            optimization_method: sgm
            overcounting: false
            penalty:
              P1: 8
              P2: 32
              p2_method: constant
              penalty_method: sgm_penalty
          cost_volume_confidence.cars_1:
            confidence_method: ambiguity
            eta_max: 0.99
            eta_step: 0.04
          cost_volume_confidence.cars_2:
            confidence_method: risk
            eta_max: 0.25
            eta_step: 0.04
          cost_volume_confidence.cars_3:
            confidence_method: interval_bounds
          disparity:
            disparity_method: wta
            invalid_disparity: NaN
          refinement:
            refinement_method: vfit
          filter:
            filter_method: median
            filter_size: 3
          validation:
            validation_method: cross_checking_fast
          filter.cars_3:
            filter_method: median_for_intervals
            filter_size: 3
            interval_indicator: cars_3
            regularization: true
            ambiguity_indicator: cars_1
    triangulation:
      save_intermediate_data: true
      method: line_of_sight_intersection
      snap_to_img1: false
    dem_generation:
      save_intermediate_data: true
      method: bulldozer_on_raster
      resolution: 2
      margin:
      - 0.1
      - 1000
      morphological_filters_size: 30
      preprocessing_median_filter_size: 5
      postprocessing_median_filter_size: 7
      dem_median_downscale: 10
      dem_min_max_downscale: 2
      fillnodata_max_search_distance: 50
      min_dem: -500
      max_dem: 1000
      height_margin: 40
      bulldozer_max_object_size: 8
      disable_bulldozer: false
      compute_stats: true
      coregistration: true
      coregistration_max_shift: 180
    point_cloud_outlier_removal.1:
      save_intermediate_data: true
      method: small_components
      save_by_pair: false
      on_ground_margin: 11
      connection_distance: 12
      nb_points_threshold: 50
      clusters_distance_threshold: 
      half_epipolar_size: 5
    point_cloud_outlier_removal.2:
      save_intermediate_data: true
      method: statistical
      save_by_pair: false
      use_median: true
      k: 50
      filtering_constant: 0
      mean_factor: 1.3
      std_dev_factor: 3
      half_epipolar_size: 5
    pc_denoising:
      save_intermediate_data: true
    point_cloud_rasterization:
      save_intermediate_data: true
      method: simple_gaussian
      dsm_radius: 1
      sigma: 
      grid_points_division_factor: 
      dsm_no_data: -32768
      texture_no_data: 
      texture_dtype: 
      msk_no_data: 255
    auxiliary_filling:
      method: auxiliary_filling_from_sensors
      mode: fill_nan
      texture_interpolator: linear
      activated: false
      use_mask: true
      save_intermediate_data: false
  all: {}
