@startuml 


  (Images) as img
  (Geometric Models) as geom
  (Input Data) as input
  (Masks) as masks
  (Input DEM) as dem
  (CARS Pipelines) as cars #red
  (Output data) as output
  (dsm.tif) as dsm
  (color.tif) as color
  (Output stats) as output_stats

  img --> input
  geom --> input
  input --> cars
  masks .right.> cars
  dem .right.> cars
  cars--> output
  output --> dsm
  output ..> color
  cars -right-> output_stats
  
  @enduml
